In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.svm import SVC

In [10]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [11]:

from sklearn.model_selection import GridSearchCV

# create model with probability=True
svc = SVC(probability=True)

param_grid = {
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    'gamma': ['auto', 'scale'],
    'C': [10, 100, 1000, 2000, 3000]
}

# GridSearch
grid = GridSearchCV(
    svc,
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=1,
    scoring='f1_weighted',
    cv=5
)

# Train
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
[CV 1/5] END ...C=10, gamma=auto, kernel=linear;, score=0.776 total time=   0.0s
[CV 2/5] END ...C=10, gamma=auto, kernel=linear;, score=0.791 total time=   0.0s
[CV 3/5] END ...C=10, gamma=auto, kernel=linear;, score=0.698 total time=   0.0s
[CV 4/5] END ...C=10, gamma=auto, kernel=linear;, score=0.924 total time=   0.0s
[CV 5/5] END ...C=10, gamma=auto, kernel=linear;, score=0.902 total time=   0.0s
[CV 1/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.867 total time=   0.0s
[CV 2/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.887 total time=   0.0s
[CV 3/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.870 total time=   0.0s
[CV 4/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.944 total time=   0.0s
[CV 5/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.943 total time=   0.0s
[CV 1/5] END .....C=10, gamma=auto, kernel=poly;, score=0.800 total time=   0.0s
[CV 2/5] END .....C=10, gamma=auto, kernel=poly;, score=0.808 total time=   0.0s
[CV 3/5] END .....C=10, gamma=auto, kernel=poly;, score=0.788 total time=   0.0s
[CV 4/5] END .....C=10, gamma=auto, kernel=poly;, score=0.925 total time=   0.0s
[CV 5/5] END .....C=10, gamma=auto, kernel=poly;, score=0.902 total time=   0.0s
[CV 1/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.763 total time=   0.0s
[CV 2/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.739 total time=   0.0s
[CV 3/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.656 total time=   0.0s
[CV 4/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END ..C=10, gamma=auto, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END ..C=10, gamma=scale, kernel=linear;, score=0.776 total time=   0.0s
[CV 2/5] END ..C=10, gamma=scale, kernel=linear;, score=0.791 total time=   0.0s
[CV 3/5] END ..C=10, gamma=scale, kernel=linear;, score=0.698 total time=   0.0s
[CV 4/5] END ..C=10, gamma=scale, kernel=linear;, score=0.924 total time=   0.0s
[CV 5/5] END ..C=10, gamma=scale, kernel=linear;, score=0.902 total time=   0.0s
[CV 1/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.867 total time=   0.0s
[CV 2/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.887 total time=   0.0s
[CV 3/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.870 total time=   0.0s
[CV 4/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.944 total time=   0.0s
[CV 5/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.943 total time=   0.0s
[CV 1/5] END ....C=10, gamma=scale, kernel=poly;, score=0.800 total time=   0.0s
[CV 2/5] END ....C=10, gamma=scale, kernel=poly;, score=0.808 total time=   0.0s
[CV 3/5] END ....C=10, gamma=scale, kernel=poly;, score=0.788 total time=   0.0s
[CV 4/5] END ....C=10, gamma=scale, kernel=poly;, score=0.925 total time=   0.0s
[CV 5/5] END ....C=10, gamma=scale, kernel=poly;, score=0.902 total time=   0.0s
[CV 1/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.763 total time=   0.0s
[CV 2/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.739 total time=   0.0s
[CV 3/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.753 total time=   0.0s
[CV 4/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.778 total time=   0.0s
[CV 5/5] END .C=10, gamma=scale, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END ..C=100, gamma=auto, kernel=linear;, score=0.776 total time=   0.0s
[CV 2/5] END ..C=100, gamma=auto, kernel=linear;, score=0.791 total time=   0.0s
[CV 3/5] END ..C=100, gamma=auto, kernel=linear;, score=0.698 total time=   0.0s
[CV 4/5] END ..C=100, gamma=auto, kernel=linear;, score=0.924 total time=   0.0s
[CV 5/5] END ..C=100, gamma=auto, kernel=linear;, score=0.902 total time=   0.0s
[CV 1/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.867 total time=   0.0s
[CV 2/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.887 total time=   0.0s
[CV 3/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.870 total time=   0.0s
[CV 4/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.944 total time=   0.0s
[CV 5/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.943 total time=   0.0s
[CV 1/5] END ....C=100, gamma=auto, kernel=poly;, score=0.822 total time=   0.0s
[CV 2/5] END ....C=100, gamma=auto, kernel=poly;, score=0.787 total time=   0.0s
[CV 3/5] END ....C=100, gamma=auto, kernel=poly;, score=0.767 total time=   0.0s
[CV 4/5] END ....C=100, gamma=auto, kernel=poly;, score=0.925 total time=   0.0s
[CV 5/5] END ....C=100, gamma=auto, kernel=poly;, score=0.902 total time=   0.0s
[CV 1/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.809 total time=   0.0s
[CV 2/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.634 total time=   0.0s
[CV 4/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.718 total time=   0.0s
[CV 5/5] END .C=100, gamma=auto, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END .C=100, gamma=scale, kernel=linear;, score=0.776 total time=   0.0s
[CV 2/5] END .C=100, gamma=scale, kernel=linear;, score=0.791 total time=   0.0s
[CV 3/5] END .C=100, gamma=scale, kernel=linear;, score=0.698 total time=   0.0s
[CV 4/5] END .C=100, gamma=scale, kernel=linear;, score=0.924 total time=   0.0s
[CV 5/5] END .C=100, gamma=scale, kernel=linear;, score=0.902 total time=   0.0s
[CV 1/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.867 total time=   0.0s
[CV 2/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.887 total time=   0.0s
[CV 3/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.870 total time=   0.0s
[CV 4/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.944 total time=   0.0s
[CV 5/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.943 total time=   0.0s
[CV 1/5] END ...C=100, gamma=scale, kernel=poly;, score=0.822 total time=   0.0s
[CV 2/5] END ...C=100, gamma=scale, kernel=poly;, score=0.787 total time=   0.0s
[CV 3/5] END ...C=100, gamma=scale, kernel=poly;, score=0.767 total time=   0.0s
[CV 4/5] END ...C=100, gamma=scale, kernel=poly;, score=0.925 total time=   0.0s
[CV 5/5] END ...C=100, gamma=scale, kernel=poly;, score=0.902 total time=   0.0s
[CV 1/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.809 total time=   0.0s
[CV 2/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.698 total time=   0.0s
[CV 4/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END C=100, gamma=scale, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END .C=1000, gamma=auto, kernel=linear;, score=0.776 total time=   0.2s
[CV 2/5] END .C=1000, gamma=auto, kernel=linear;, score=0.791 total time=   0.1s
[CV 3/5] END .C=1000, gamma=auto, kernel=linear;, score=0.698 total time=   0.2s
[CV 4/5] END .C=1000, gamma=auto, kernel=linear;, score=0.924 total time=   0.1s
[CV 5/5] END .C=1000, gamma=auto, kernel=linear;, score=0.902 total time=   0.3s
[CV 1/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.826 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.867 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.852 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.925 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=auto, kernel=rbf;, score=0.924 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.822 total time=   0.2s
[CV 2/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.766 total time=   0.2s
[CV 3/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.767 total time=   0.1s
[CV 4/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.925 total time=   0.2s
[CV 5/5] END ...C=1000, gamma=auto, kernel=poly;, score=0.902 total time=   0.3s
[CV 1/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.792 total time=   0.0s
[CV 2/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.698 total time=   0.0s
[CV 4/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END C=1000, gamma=auto, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END C=1000, gamma=scale, kernel=linear;, score=0.776 total time=   0.3s
[CV 2/5] END C=1000, gamma=scale, kernel=linear;, score=0.791 total time=   0.1s

[CV 3/5] END C=1000, gamma=scale, kernel=linear;, score=0.698 total time=   0.3s
[CV 4/5] END C=1000, gamma=scale, kernel=linear;, score=0.924 total time=   0.1s
[CV 5/5] END C=1000, gamma=scale, kernel=linear;, score=0.902 total time=   0.1s
[CV 1/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.847 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.867 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.852 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.925 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=scale, kernel=rbf;, score=0.924 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.822 total time=   0.2s
[CV 2/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.766 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.767 total time=   0.1s
[CV 4/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.925 total time=   0.2s
[CV 5/5] END ..C=1000, gamma=scale, kernel=poly;, score=0.902 total time=   0.5s
[CV 1/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.809 total time=   0.0s
[CV 2/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.698 total time=   0.0s
[CV 4/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END C=1000, gamma=scale, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END .C=2000, gamma=auto, kernel=linear;, score=0.776 total time=   0.3s
[CV 2/5] END .C=2000, gamma=auto, kernel=linear;, score=0.791 total time=   0.2s
[CV 3/5] END .C=2000, gamma=auto, kernel=linear;, score=0.698 total time=   0.4s
[CV 4/5] END .C=2000, gamma=auto, kernel=linear;, score=0.924 total time=   0.8s
[CV 5/5] END .C=2000, gamma=auto, kernel=linear;, score=0.902 total time=   0.5s
[CV 1/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.826 total time=   0.0s
[CV 2/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.867 total time=   0.0s
[CV 3/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.852 total time=   0.0s
[CV 4/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.887 total time=   0.0s
[CV 5/5] END ....C=2000, gamma=auto, kernel=rbf;, score=0.904 total time=   0.0s
[CV 1/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.822 total time=   0.7s
[CV 2/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.766 total time=   0.3s
[CV 3/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.767 total time=   0.5s
[CV 4/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.925 total time=   0.6s
[CV 5/5] END ...C=2000, gamma=auto, kernel=poly;, score=0.902 total time=   0.5s
[CV 1/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.792 total time=   0.0s
[CV 2/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.698 total time=   0.0s
[CV 4/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END C=2000, gamma=auto, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END C=2000, gamma=scale, kernel=linear;, score=0.776 total time=   0.3s
[CV 2/5] END C=2000, gamma=scale, kernel=linear;, score=0.791 total time=   0.2s
[CV 3/5] END C=2000, gamma=scale, kernel=linear;, score=0.698 total time=   0.3s
[CV 4/5] END C=2000, gamma=scale, kernel=linear;, score=0.924 total time=   0.3s
[CV 5/5] END C=2000, gamma=scale, kernel=linear;, score=0.902 total time=   0.4s
[CV 1/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.826 total time=   0.0s
[CV 2/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.867 total time=   0.0s
[CV 3/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.852 total time=   0.0s
[CV 4/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.887 total time=   0.0s
[CV 5/5] END ...C=2000, gamma=scale, kernel=rbf;, score=0.904 total time=   0.0s
[CV 1/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.822 total time=   0.5s
[CV 2/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.766 total time=   0.2s
[CV 3/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.767 total time=   0.5s
[CV 4/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.925 total time=   0.5s
[CV 5/5] END ..C=2000, gamma=scale, kernel=poly;, score=0.902 total time=   0.5s
[CV 1/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.809 total time=   0.0s
[CV 2/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.698 total time=   0.0s
[CV 4/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END C=2000, gamma=scale, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END .C=3000, gamma=auto, kernel=linear;, score=0.776 total time=   0.6s
[CV 2/5] END .C=3000, gamma=auto, kernel=linear;, score=0.791 total time=   0.6s
[CV 3/5] END .C=3000, gamma=auto, kernel=linear;, score=0.698 total time=   0.5s
[CV 4/5] END .C=3000, gamma=auto, kernel=linear;, score=0.924 total time=   0.4s
[CV 5/5] END .C=3000, gamma=auto, kernel=linear;, score=0.902 total time=   0.5s
[CV 1/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.826 total time=   0.0s
[CV 2/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.867 total time=   0.0s
[CV 3/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.852 total time=   0.0s
[CV 4/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.847 total time=   0.0s
[CV 5/5] END ....C=3000, gamma=auto, kernel=rbf;, score=0.883 total time=   0.0s
[CV 1/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.822 total time=   0.7s
[CV 2/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.766 total time=   0.6s
[CV 3/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.767 total time=   0.6s
[CV 4/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.925 total time=   0.9s
[CV 5/5] END ...C=3000, gamma=auto, kernel=poly;, score=0.902 total time=   1.3s
[CV 1/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.792 total time=   0.0s
[CV 2/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.698 total time=   0.0s
[CV 4/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END C=3000, gamma=auto, kernel=sigmoid;, score=0.767 total time=   0.0s
[CV 1/5] END C=3000, gamma=scale, kernel=linear;, score=0.776 total time=   0.5s
[CV 2/5] END C=3000, gamma=scale, kernel=linear;, score=0.791 total time=   0.4s
[CV 3/5] END C=3000, gamma=scale, kernel=linear;, score=0.698 total time=   0.6s
[CV 4/5] END C=3000, gamma=scale, kernel=linear;, score=0.924 total time=   0.3s
[CV 5/5] END C=3000, gamma=scale, kernel=linear;, score=0.902 total time=   0.7s
[CV 1/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.826 total time=   0.0s
[CV 2/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.867 total time=   0.0s
[CV 3/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.852 total time=   0.0s
[CV 4/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.847 total time=   0.0s
[CV 5/5] END ...C=3000, gamma=scale, kernel=rbf;, score=0.883 total time=   0.0s
[CV 1/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.822 total time=   0.7s
[CV 2/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.766 total time=   0.4s
[CV 3/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.767 total time=   1.0s
[CV 4/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.925 total time=   0.8s
[CV 5/5] END ..C=3000, gamma=scale, kernel=poly;, score=0.902 total time=   1.2s
[CV 1/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.809 total time=   0.0s
[CV 2/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.715 total time=   0.0s
[CV 3/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.698 total time=   0.0s
[CV 4/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.796 total time=   0.0s
[CV 5/5] END C=3000, gamma=scale, kernel=sigmoid;, score=0.767 total time=   0.0s

GridSearchCV(cv=5, estimator=SVC(probability=True), n_jobs=1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [12]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [13]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9100355779243318

In [14]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[80  5]
 [ 7 42]]

In [15]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93        85
           1       0.89      0.86      0.88        49

    accuracy                           0.91       134
   macro avg       0.91      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134

In [16]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9539015606242497

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.027507,0.022104,0.002647,1.042917e-03,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
1,0.011189,0.001193,0.002248,4.620875e-04,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
2,0.013777,0.007207,0.001675,7.497570e-04,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
3,0.010812,0.004213,0.002621,1.287562e-03,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.762677,0.738916,0.655795,0.796284,0.766556,0.744045,0.047743,39
4,0.017058,0.003962,0.002396,9.975050e-04,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
5,0.009337,0.001056,0.001975,5.257956e-04,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
6,0.014814,0.003000,0.002535,9.317415e-04,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
7,0.011867,0.005269,0.002285,1.296077e-03,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.762677,0.738916,0.753180,0.778067,0.766556,0.759879,0.013172,31
8,0.036722,0.012728,0.001607,4.957006e-04,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
9,0.011977,0.005854,0.001734,9.101230e-04,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
10,0.032616,0.009690,0.001404,7.942065e-04,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
11,0.008677,0.003145,0.002069,5.789501e-04,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.808927,0.714931,0.633719,0.718497,0.766556,0.728526,0.058625,40
12,0.037300,0.008708,0.001614,8.124327e-04,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
13,0.011887,0.005756,0.001323,4.396633e-04,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
14,0.060338,0.022151,0.001639,4.937088e-04,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
15,0.011464,0.001893,0.002503,5.328108e-04,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
16,0.263958,0.072764,0.001921,9.335343e-04,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
17,0.033109,0.008169,0.002379,1.343910e-03,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.925272,0.923510,0.878708,0.039503,6
18,0.282142,0.053625,0.001216,4.097360e-04,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
19,0.010326,0.003331,0.002219,4.423398e-04,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
20,0.274893,0.105905,0.001960,8.781372e-04,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
21,0.039558,0.006550,0.002020,6.254154e-04,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.847141,0.866968,0.851527,0.925272,0.923510,0.882884,0.034529,5
22,0.310613,0.139726,0.001597,5.852658e-04,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
23,0.005373,0.000359,0.000998,4.623108e-07,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
24,0.548812,0.191768,0.001237,3.928008e-04,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
25,0.037402,0.003381,0.001427,4.756553e-04,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
26,0.608451,0.129300,0.002053,1.122091e-03,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
27,0.006172,0.001503,0.001076,6.975817e-04,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
28,0.388093,0.077680,0.001239,4.456208e-04,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
29,0.051516,0.014669,0.001795,7.458305e-04,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
30,0.519309,0.118508,0.001417,4.807994e-04,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
31,0.005196,0.000606,0.001031,6.254032e-05,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
32,0.622297,0.058274,0.001714,8.877398e-04,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
33,0.061617,0.020059,0.001259,3.759215e-04,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
34,0.940316,0.252544,0.001203,3.959829e-04,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
35,0.006048,0.002277,0.001446,8.222115e-04,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
36,0.589482,0.147631,0.001466,5.580221e-04,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
37,0.062646,0.017258,0.001721,8.703397e-04,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
38,0.924673,0.286168,0.001201,3.973282e-04,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
39,0.008410,0.003082,0.002212,6.841475e-04,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32

In [19]:
age_input = float(input("Enter Age: "))
salary_input = float(input("Enter Estimated Salary: "))
gender_input = int(input("Gender Male? (1 = Male, 0 = Female): "))

Enter Age: 33
Enter Estimated Salary: 30000
Gender Male? (1 = Male, 0 = Female): 1

In [20]:
# important: apply same scaling
user_data = sc.transform([[age_input, salary_input, gender_input]])

C:\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"

In [21]:
Future_Prediction = grid.predict(user_data)

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[0]